//! Provider trait + supporting types.
//!
//! Capability-negotiated LLM backend abstraction (ADR-005). Each backend
//! (Ollama baseline, OpenAI, llama.cpp, vLLM, MLX, ...) advertises what it
//! supports via [`ProviderCapabilities`]; the agent loop adapts (no native
//! tools → prompt-based selection, no structured output → text parsing).
//! Per-provider quirks live in adapter crates and never leak through here.

use argos_core::{Embedding, Result};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};

/// Options passed to [`Provider::complete`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CompletionOptions {
    /// Sampling temperature (0.0 = greedy, higher = more random).
    pub temperature: f64,
    /// Maximum tokens to generate. `None` lets the provider pick its default.
    pub max_tokens: Option<usize>,
    /// Whether the caller wants a streamed response (provider may ignore).
    pub stream: bool,
    /// Optional system prompt prepended to the conversation.
    pub system_prompt: Option<String>,
}

impl Default for CompletionOptions {
    /// Sensible defaults: non-streaming, no token cap, no system prompt.
    fn default() -> Self {
        Self {
            temperature: 0.7,
            max_tokens: None,
            stream: false,
            system_prompt: None,
        }
    }
}

/// Token accounting for a single completion.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TokenUsage {
    /// Tokens consumed by the prompt.
    pub prompt_tokens: u32,
    /// Tokens generated by the model.
    pub completion_tokens: u32,
}

/// Why the completion stopped.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FinishReason {
    /// The model reached a natural stop.
    Stop,
    /// The maximum token limit was hit.
    Length,
    /// The model requested a tool invocation.
    ToolCall,
    /// The completion errored.
    Error,
}

/// The result of a [`Provider::complete`] call.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Completion {
    /// The generated text.
    pub text: String,
    /// Token usage for this completion.
    pub usage: TokenUsage,
    /// Why generation stopped.
    pub finish_reason: FinishReason,
}

/// Capabilities a provider advertises, used by the agent loop to adapt.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProviderCapabilities {
    /// Supports streaming completions.
    pub supports_streaming: bool,
    /// Supports native function/tool calling.
    pub supports_function_calling: bool,
    /// Accepts image inputs.
    pub supports_vision: bool,
    /// Can produce embeddings via [`Provider::embed`].
    pub supports_embeddings: bool,
    /// Maximum context window in tokens.
    pub max_context: usize,
}

/// Capability-negotiated LLM provider abstraction.
///
/// `complete` drives the agent loop; `embed` backs workflow intelligence and
/// the LLM-Wiki ingest/query operations. `capabilities` is queried once so the
/// loop can adapt without leaking provider quirks. `health_check` verifies
/// reachability (used by `argos init` and provider switch).
#[async_trait]
pub trait Provider: Send + Sync {
    /// Generate a completion for `prompt` under `options`.
    async fn complete(&self, prompt: &str, options: &CompletionOptions) -> Result<Completion>;
    /// Embed `text` into a dense vector (used by workflow intelligence + wiki).
    async fn embed(&self, text: &str) -> Result<Embedding>;
    /// Advertise what this provider supports.
    async fn capabilities(&self) -> ProviderCapabilities;
    /// Verify the provider is reachable.
    async fn health_check(&self) -> Result<()>;
}

#[cfg(test)]
mod tests {
    use super::*;

    /// In-memory provider stub returning canned, deterministic responses.
    struct StubProvider {
        caps: ProviderCapabilities,
    }

    #[async_trait::async_trait]
    impl Provider for StubProvider {
        async fn complete(
            &self,
            prompt: &str,
            _options: &CompletionOptions,
        ) -> argos_core::Result<Completion> {
            Ok(Completion {
                text: format!("echo:{prompt}"),
                usage: TokenUsage {
                    prompt_tokens: prompt.len() as u32,
                    completion_tokens: 5,
                },
                finish_reason: FinishReason::Stop,
            })
        }

        async fn embed(&self, text: &str) -> argos_core::Result<argos_core::Embedding> {
            // Deterministic stub embedding: one dimension per byte value.
            Ok(text.bytes().map(|b| b as f32).collect())
        }

        async fn capabilities(&self) -> ProviderCapabilities {
            self.caps.clone()
        }

        async fn health_check(&self) -> argos_core::Result<()> {
            Ok(())
        }
    }

    fn stub_caps() -> ProviderCapabilities {
        ProviderCapabilities {
            supports_streaming: false,
            supports_function_calling: true,
            supports_vision: false,
            supports_embeddings: true,
            max_context: 8192,
        }
    }

    #[test]
    fn provider_trait_can_be_referenced() {
        let p: &dyn Provider = &StubProvider { caps: stub_caps() };
        let _ = p;
    }

    #[test]
    fn completion_options_constructs_with_defaults() {
        let opts = CompletionOptions::default();
        assert!(!opts.stream);
        assert_eq!(opts.max_tokens, None);
        assert_eq!(opts.system_prompt, None);
        // Sensible default temperature is present and finite.
        assert!(opts.temperature.is_finite());
    }

    #[test]
    fn completion_constructs() {
        let c = Completion {
            text: "hello".into(),
            usage: TokenUsage {
                prompt_tokens: 3,
                completion_tokens: 2,
            },
            finish_reason: FinishReason::Stop,
        };
        assert_eq!(c.text, "hello");
        assert_eq!(c.usage.prompt_tokens, 3);
        assert_eq!(c.usage.completion_tokens, 2);
    }

    #[test]
    fn provider_capabilities_constructs() {
        let caps = stub_caps();
        assert!(caps.supports_function_calling);
        assert!(caps.supports_embeddings);
        assert!(!caps.supports_vision);
        assert_eq!(caps.max_context, 8192);
    }

    #[test]
    fn finish_reason_variants_exist() {
        // Every advertised variant is constructible and distinguishable.
        let variants = [
            FinishReason::Stop,
            FinishReason::Length,
            FinishReason::ToolCall,
            FinishReason::Error,
        ];
        assert_eq!(variants.len(), 4);
        assert_ne!(FinishReason::Stop, FinishReason::Length);
        assert_ne!(FinishReason::ToolCall, FinishReason::Error);
    }

    #[tokio::test]
    async fn stub_provider_complete_returns_canned_response() {
        let p = StubProvider { caps: stub_caps() };
        let opts = CompletionOptions::default();
        let completion = p.complete("hello", &opts).await.unwrap();
        assert_eq!(completion.text, "echo:hello");
        assert_eq!(completion.finish_reason, FinishReason::Stop);
        assert_eq!(completion.usage.prompt_tokens, 5);
        assert_eq!(completion.usage.completion_tokens, 5);
    }

    #[tokio::test]
    async fn stub_provider_embed_returns_nonempty_vector() {
        let p = StubProvider { caps: stub_caps() };
        let emb = p.embed("ab").await.unwrap();
        assert_eq!(emb.len(), 2);
        assert!(!emb.is_empty());
    }

    #[tokio::test]
    async fn stub_provider_capabilities_advertised() {
        let p = StubProvider { caps: stub_caps() };
        let caps = p.capabilities().await;
        assert!(caps.supports_embeddings);
        assert!(caps.supports_function_calling);
    }

    #[tokio::test]
    async fn stub_provider_health_check_ok() {
        let p = StubProvider { caps: stub_caps() };
        assert!(p.health_check().await.is_ok());
    }
}
